version: '2'
services:
    web:
        build: .
        image: django-sandbox:latest
        command: sh docker-entrypoint.sh
        volumes:
            - .:/code
        ports:
            - "8000:8000"
