# Generated by Django 2.2.1 on 2019-05-24 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Aberta'), (2, 'Finalizada')], default=1)),
                ('descricao', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
                ('cidade', models.CharField(max_length=256)),
                ('cep', models.CharField(max_length=256)),
                ('endereco', models.CharField(max_length=256)),
                ('num_endereco', models.IntegerField()),
                ('comp_endereco', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demanda',
            },
        ),
    ]
