# Generated by Django 2.2.1 on 2019-05-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('telefone', models.IntegerField(max_length=13)),
            ],
            options={
                'db_table': 'anunciante',
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Aberta'), (2, 'Finalizada')], default=1)),
                ('descricao', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
                ('cidade', models.CharField(max_length=256)),
                ('cep', models.CharField(max_length=256)),
                ('endereco', models.CharField(max_length=256)),
                ('num_endereco', models.IntegerField(max_length=7)),
                ('comp_endereco', models.CharField(max_length=256)),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Anunciante')),
            ],
            options={
                'db_table': 'demanda',
            },
        ),
    ]
