# Generated by Django 2.2.1 on 2019-05-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190522_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciante',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='num_endereco',
            field=models.IntegerField(),
        ),
    ]
